DROP TABLE IF EXISTS TOUR;

CREATE TABLE TOUR
(
    TOUR_ID   INT         NOT NULL AUTO_INCREMENT,
    DIRECTION VARCHAR(50) NOT NULL UNIQUE,
    DATE_TOUR DATE        NOT NULL,
    PRIMARY KEY (TOUR_ID)
);